### ISSUE TITLE
Actions not working

### ISSUE THREAD

**Issue by mrustl** [technologiestiftung/flusshygiene-opencpu-base#14]
I had problems to get Github actions to work. This is why according to Github:

________________________________________
Von: GitHub Developer Support [developer@githubsupport.com]
Gesendet: Dienstag, 1. Oktober 2019 16:06
An: Michael Rustler
Cc: Michael Rustler
Betreff: [GitHub Developer Support] - Actions not working

## Please do not write below this line ##

Your request has been updated.

You can add a comment by replying to this email.

[https://github.zendesk.com/system/photos/3602/5132/1212/MVIMG_20190414_002631.jpg]

Thomas Baillie (GitHub Developer Support)

Oct 1, 2:05 PM UTC

Hi Michael,

I've just heard back from the Actions team and there appears to be a bug that's preventing the Actions tab from rendering correctly. It looks like the issue is caused by this line:

https://github.com/mrustl/flusshygiene-opencpu-base/blob/master/.github/workflows/build-and-push-image.yml#L13

Can you convert this variable to a String by surrounding it in ' characters? That should at least fix the Actions tab from showing an error for now.

Thanks,
Thomas
GitHub Support

👉 Find answers to common questions and learn with other GitHub users in our new GitHub Community Forum<https://github.community/?utm_source=halp&utm_medium=email>.

[https://github.zendesk.com/system/photos/3602/5132/1212/MVIMG_20190414_002631.jpg]

Thomas Baillie (GitHub Developer Support)

Oct 1, 1:54 PM UTC

Hi Michael,

Thanks for getting in touch and sorry for the trouble! I've escalated this issue to the Actions team to take a look into. We can't give an ETA on a fix, but we'll get back to you as soon as we have some news.

Thanks,
Thomas
GitHub Support

👉 Find answers to common questions and learn with other GitHub users in our new GitHub Community Forum<https://github.community/?utm_source=halp&utm_medium=email>.

[https://secure.gravatar.com/avatar/61a53e30e855a30fe3d6c4d3b94c72f1?size=40&default=https%3A%2F%2Fassets.zendesk.com%2Fimages%2F2016%2Fdefault-avatar-80.png&r=g]

Michael Rustler

Oct 1, 12:03 PM UTC

Hi, why is Actions not working for: https://github.com/mrustl/flusshygiene-opencpu-base/actions

While it is running on:
https://github.com/technologiestiftung/flusshygiene-opencpu-base/actions

This email is a service from GitHub Developer Support.
[PMRW6M-EVWD]

**Comment by fabianmoronzirfas** [comment]
Awesome. Thank you!
