### ISSUE TITLE
Compiler options needed to install "rstanarm" 

### ISSUE THREAD

**Issue by hsonne** [technologiestiftung/flusshygiene-opencpu-base#2]
https://github.com/KWB-R/kwb.flusshygiene.app/blob/168b36210a0d6cc7b03dfc445d28675b5b64c6e8/.travis.yml

(copied from: https://github.com/stan-dev/rstanarm/blob/master/.travis.yml)

**Comment by fabianmoronzirfas** [comment]
Jiiihhaaa build is passing in 20 mins on Github https://github.com/technologiestiftung/flusshygiene-opencpu-base/runs/210462820#step:6:10802

Can be found here --> https://hub.docker.com/r/technologiestiftung/flusshygiene-opencpu-base
